name: server_jars_api_dart
description: A Dart wrapper for the ServerJars API
version: 1.0.0
# homepage: https://github.com/LethalBoar70923/serverjars-dart-api-wrapper

environment:
  sdk: '>=2.14.4 <3.0.0'

# dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
